java:
  applicationPort: 8093
  aadIdentityName: rd
  environment:
    POSTGRES_HOST: rd-profile-sync-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_NAME: dbsyncdata
    POSTGRES_USER: dbsyncdata@rd-profile-sync-postgres-db-{{ .Values.global.environment }}
    POSTGRES_PORT: 5432
  image: 'hmctspublic.azurecr.io/hmcts/draft-store-service:latest'
  keyVaults:
    rd:
      secrets:
        - s2s-secret
        - profile-sync-POSTGRES-PASS
        - AppInsightsInstrumentationKey
