spring:
  application:
    name: rd-profile-sync

server:
  port: 8080


idam:
  api:
    url: ${IDAM_URL:https://idam-api.preview.platform.hmcts.net}
    client-id: ${OAUTH2_CLIENT_ID:rd-professional-api}
    redirect-uri: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-preview.service.core-compute-preview.internal/oauth2redirect}
    authorization: ${OAUTH2_AUTH:bWFyay5udXRoYWxhcGF0aUBobWN0cy5uZXQ6UGE1NXdvcmQxMQ==}
    client-authorization: ${OAUTH2_CLIENT_AUTH:cmQtcHJvZmVzc2lvbmFsLWFwaTpjYzVmMmE2LTk2OTAtMTFlOS1iYzQyLTUyNmFmNzc2NGY2NA==}
  s2s-auth:
    totp_secret: ${S2S_SECRET:K6KA6PRLRFWQLSD6}
    microservice: rd_professional_api
    url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

userprofile:
  api:
    url: ${USER_PROFILE_URL:http://rd-user-profile-api-preview.service.core-compute-preview.internal}